name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows run workflow from Actions tab
  workflow_dispatch:

jobs:
  ts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Yarn install
        run: yarn
        
      - name: TSC
        run: yarn tsc
